# Generated by Django 5.0.8 on 2024-08-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),

    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='full_description',
            field=models.TextField(default=None, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='short_description',
            field=models.TextField(verbose_name='короткое описание'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='publicationcomment',
            name='author_name',
            field=models.CharField(default=None, max_length=200, verbose_name='имя автора'),
        ),
    ]
