# Generated by Django 5.0.8 on 2024-08-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_delete_feedback'),

    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_kg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='full_description_en',
            field=models.TextField(default=None, null=True, verbose_name='полное описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='full_description_kg',
            field=models.TextField(default=None, null=True, verbose_name='полное описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='full_description_ru',
            field=models.TextField(default=None, null=True, verbose_name='полное описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_kg',
            field=models.TextField(null=True, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='короткое описание'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.TextField(null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_kg',
            field=models.TextField(null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='название'),
        ),
    ]
