# Generated by Django 5.0.8 on 2024-08-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_title_en_category_title_kg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='publicationcomment',
            options={'verbose_name': 'Комментарий Публикации', 'verbose_name_plural': 'Комментарии публикаций'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_en',
            new_name='title_en_US',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='title_en',
            new_name='title_en_US',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='title_kg',
            new_name='title_ky',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='full_description_en',
            new_name='full_description_en_US',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='full_description_kg',
            new_name='full_description_ky',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='short_description_en',
            new_name='short_description_en_US',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='short_description_kg',
            new_name='short_description_ky',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_en',
            new_name='title_en_US',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
