# Generated by Django 5.0.8 on 2024-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='title_en_US',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='title_en_US',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='full_description_en_US',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='short_description_en_US',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='title_en_US',
        ),
    ]
